//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class YedekOrder
    {
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<int> empId { get; set; }
        public Nullable<int> customerId { get; set; }
        public int orderId { get; set; }
    }
}
